# Generated by Django 5.1.5 on 2025-01-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testimoinal_alter_clientlogo_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimoinal',
            new_name='Testimonial',
        ),
    ]
